# Site settings
title: Casper Woroszylo
email: cerosz@gmail.com
description: "I'm a Postdoctoral fellow at the MBI at Ohio State. I'm interested in the variability and dynamics associated with physical systems."
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://casperw.github.io"/ # the base hostname & protocol for your site
github_username:  casperw
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  
markdown: kramdown
theme: minima

# needed for CI builds:
exclude: [vendor]