project:
  type: website

website:
  title: "Such and Such"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - posts.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

